apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-bot-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-bot-backend
  template:
    metadata:
      labels:
        app: devops-bot-backend
    spec:
      containers:
      - name: backend
        image: devops-bot-backend:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/database
          name: database-storage
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: database-pvc

