apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-bot-combined-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-bot
  template:
    metadata:
      labels:
        app: devops-bot
    spec:
      containers:
      - name: backend
        image: deeeye2/devops-bot-backend-v1:latest
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        volumeMounts:
        - mountPath: /app/database
          name: database-storage
      - name: devops-bot-ui
        image: deeeye2/devops-bot-ui:latest
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://localhost:5001"
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: database-pvc
