apiVersion: v1
kind: Service
metadata:
  name: devops-bot-combined-service
spec:
  type: NodePort
  selector:
    app: devops-bot
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: backend
    protocol: TCP
    port: 5000
    targetPort: 5001
    nodePort: 30081
