apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minikube-pvc-binding
  namespace: default
subjects:
- kind: User
  name: system:node:minikube
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pv-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pv-access
  namespace: default
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "watch", "list"]
